### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by In-f3rno** [cburrows1/AlgoRythm#44]
I want to make this Visualizer a part of my GUI. I made a J.A.R.V.I.S, so i just want to know how to use this in Qt studio. Can you help me out?
@Laurence-RM

**Comment by Laurence-RM** [comment]
Not sure how you can integrate it with Qt since this uses Pygame to render the window and is designed to be its own standalone application. Nor do I have any experience with Qt Design Studio. However, it may be possible with some tweaking as long as it can run Python. 

This is a student project that we are submitting tomorrow and we don't have any further expectations to work on it.
Good luck and thanks for checking it out though!
